#!/usr/bin/env python3
"""golden_to_header.py - turn kernels/golden/*.txt into golden_data.h.

Keeps golden vectors human-diffable in text form (the source of truth,
reviewable in PRs) while giving the on-target harness a dependency-free
compiled-in copy so it needs no filesystem under QEMU / the ISS.

Usage:  python3 harness/golden_to_header.py kernels/golden harness/golden_data.h
"""
import sys, os, glob

def main(golden_dir, out_path):
    files = sorted(glob.glob(os.path.join(golden_dir, "*.txt")))
    with open(out_path, "w") as o:
        o.write("/* AUTO-GENERATED by golden_to_header.py - do not edit. */\n")
        o.write("#ifndef GOLDEN_DATA_H\n#define GOLDEN_DATA_H\n")
        o.write("#include <stdint.h>\n\n")
        for path in files:
            with open(path) as f:
                header = f.readline().strip()      # "# name count"
                _, name, count = header.split()
                vals = [line.strip() for line in f if line.strip() != ""]
            assert len(vals) == int(count), f"{name}: {len(vals)} != {count}"
            o.write(f"static const int64_t golden_{name}[{count}] = {{\n")
            for i in range(0, len(vals), 8):
                o.write("    " + ", ".join(vals[i:i+8]) + ",\n")
            o.write("};\n")
            o.write(f"#define GOLDEN_{name.upper()}_N {count}\n\n")
        o.write("#endif /* GOLDEN_DATA_H */\n")
    print(f"wrote {out_path} from {len(files)} golden files")

if __name__ == "__main__":
    d = sys.argv[1] if len(sys.argv) > 1 else "kernels/golden"
    out = sys.argv[2] if len(sys.argv) > 2 else "harness/golden_data.h"
    main(d, out)
