#!/usr/bin/env python3
"""gen-capabilities.py - render the DSP-arm "What runs today" capability table
into README.md between the <!-- BEGIN/END capability-table --> markers.

The point is anti-drift: the kernel roster is derived from a CODE source of
truth, not hand-maintained, so the table cannot silently disagree with the
repo. The roster is cross-checked three ways and any mismatch is a hard error:

    kernels/golden/*.txt   (one golden vector file per kernel)
  == k_*_ref decls in kernels/dsp_kernels.h   (the contract)
  == the KERNELS map below                    (labels live here)

So adding an 8th kernel without updating the docs fails the build, and the
table can never list a kernel that does not exist. The per-datapath STATUS
labels are declared here (intent); they are enforced *live* by
`make compare-dsp`, which gates CI on actual bit-exactness.

Usage:
    tools/gen-capabilities.py            # rewrite the table in README.md
    tools/gen-capabilities.py --check    # fail (exit 1) if it is stale; no write
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
GOLDEN = ROOT / "kernels" / "golden"
HEADER = ROOT / "kernels" / "dsp_kernels.h"
README = ROOT / "README.md"
BEGIN = "<!-- BEGIN capability-table -->"
END = "<!-- END capability-table -->"

# kernel id (== golden filename == k_<id>_ref) -> human workload label.
# Adding a kernel means adding a golden vector, a k_<id>_ref decl, AND a row
# here - the cross-check below enforces all three stay in lockstep.
KERNELS = {
    "fir_q15":       "FIR filter (Q15)",
    "biquad_q14":    "biquad IIR, DF-I (Q14)",
    "dotprod_q15":   "real dot product (Q15 -> i64)",
    "cdotprod_q15":  "complex dot product (Q15)",
    "fft64_q15":     "64-pt radix-2 FFT (Q15)",
    "requantize_s8": "NN requantize (i32 -> i8)",
    "matmul_s8":     "int8 GEMM (i32 accumulate)",
}

# Per-datapath status (intent; `make compare-dsp` enforces RVV bit-exactness).
RVV_STATUS = "&#10003; bit-exact"   # all implemented + verified under QEMU
HIFI_STATUS = "seam"                # firewall drop-in (green via _ref out here)


def roster_from_golden():
    return sorted(p.stem for p in GOLDEN.glob("*.txt"))


def roster_from_header():
    return sorted(set(re.findall(r"\bk_([a-z0-9_]+)_ref\b", HEADER.read_text())))


def render():
    golden = roster_from_golden()
    header = roster_from_header()
    declared = sorted(KERNELS)
    if not (golden == header == declared):
        sys.stderr.write(
            "capability roster MISMATCH (keep all three in lockstep):\n"
            f"  kernels/golden/*.txt : {golden}\n"
            f"  dsp_kernels.h k_*_ref: {header}\n"
            f"  gen-capabilities map : {declared}\n")
        raise SystemExit(2)

    rows = [f"| `{k}` | {KERNELS[k]} | {RVV_STATUS} | {HIFI_STATUS} |" for k in golden]
    return "\n".join([
        BEGIN,
        "",
        "### What runs today",
        "",
        "_Generated by `tools/gen-capabilities.py` (`make capabilities`) from the "
        "golden roster - do not edit by hand._",
        "",
        f"The DSP arm has **{len(golden)}** fixed-point kernels, each checked "
        "**bit-exact** against the scalar golden oracle:",
        "",
        "| kernel | workload | RVV 1.0 (rv64) | HiFi (firewall) |",
        "|---|---|---|---|",
        *rows,
        "",
        "Legs: `riscv` (rv64, xPack GCC) &middot; `m7` (Cortex-M7, arm-none-eabi) "
        "&middot; `xtensa` (dc233c scalar baseline, Zephyr SDK). RVV status is "
        "enforced live by `make compare-dsp`; HiFi kernels are filled behind the "
        "firewall.",
        "",
        END,
    ])


def main(argv):
    check = "--check" in argv
    table = render()
    readme = README.read_text()
    if BEGIN not in readme or END not in readme:
        sys.stderr.write(f"markers {BEGIN} / {END} not found in README.md\n")
        return 2
    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: table,
                 readme, count=1, flags=re.S)
    if check:
        if new != readme:
            sys.stderr.write(
                "capability table is STALE - run `make capabilities` and commit.\n")
            return 1
        print("capability table up to date.")
        return 0
    README.write_text(new)
    print(f"capability table rendered ({len(KERNELS)} kernels).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
